# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.3+3

environment:
  sdk: ^3.5.3

# App dependencies
dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.5
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.5
  firebase_remote_config: ^5.4.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  get: ^4.7.2
  google_mobile_ads: ^5.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    
flutter_icons:
  image_path: "assets/images/Zen.png"
  android: true
  ios: false
  remove_alpha_ios: false  # Remove alpha channel for iOS app store


flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/
